name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-test: ['12', '14', '16']
    name: Test on Node ${{ matrix.node-test }}
    steps:
      - uses: actions/checkout@v2
      - name: NPM Install and Build
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-test }}
      - run: npm install
      - run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-build: ['16']
    name: Build on node ${{ matrix.node-build }}
    steps:
      - uses: actions/checkout@v2
      - name: NPM Install and Build
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-build }}
      - run: npm install
      - run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy static build to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
